name: goquorum # you probably want to 'snapcraft register <name>'
base: core # the base snap is the execution environment for this snap
version: '2.2.3+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Testing Quorum binaries publishing # 79 char long summary
description: |
  Testing Quorum binary publishing to Snap Store

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
